min_acl: public
title: TheMovieDatabase
module: TheMovieDatabase
module_version: 0.1.0
readme: README.md
author: Ruben Santiago
github_url: https://github.com/rubensantiago/themoviedatabase
documentation: "docs/Guides/*.md"
source_directory: TheMovieDatabase
output: docs/public
build_tool_arguments:
    - -workspace
    - ../Example/TheMovieDatabase.xcworkspace
    - -scheme
    - Movies
    - -sdk
    - iphonesimulator
theme: apple
head: "<style>
header {
	background-color: #135aad;
}
header p {
	color: white;
}
.sidebar {
	width: 249px;
}
</style>"
